export const employees = {
    E01: {
        title: 'Waitress',
        image: '/img/employee/01.svg',
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'misc',
        description: 'Get $3 cash.\nWin ties against\nrestaurant with\nfewer waitresses',
    },
    E02: {
        title: 'Management Trainee',
        image: '/img/employee/02.svg',
        promotion: ['E09', 'E10', 'E11'],
        begin: true,
        limited: false,
        salary: false,
        amount: 18,
        category: 'management',
        description: '2',
    },
    E03: {
        title: 'Pricing Manager',
        image: '/img/employee/03.svg',
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'pricing',
        description: 'Price -$1',
    },
    E04: {
        title: 'Recruiting Girl',
        image: '/img/employee/04.svg',
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'hr',
        description: 'Hire 1 person',
    },
    E05: {
        title: 'Trainer',
        image: '/img/employee/05.svg',
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'hr',
        description: 'Train 1 person',
    },
    E06: {
        title: 'Errand Boy',
        image: '/img/employee/06.svg',
        promotion: ['E12'],
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'drink',
        description: 'Get 1 drink of any type',
    },
    E07: {
        title: 'Marketing Trainee',
        image: '/img/employee/07.svg',
        promotion: ['E13'],
        begin: true,
        limited: false,
        salary: false,
        distanceType: 'walk',
        distance: 2,
        amount: 12,
        category: 'marketing',
        description: 'Place billboard,\nman duration 2',
    },
    E08: {
        title: 'Kitchen Trainee',
        image: '/img/employee/08.svg',
        promotion: ['E14', 'E15'],
        begin: true,
        limited: false,
        salary: false,
        amount: 12,
        category: 'food',
        description: 'Produce 1 burger\nor 1 pizza',
    },
    E09: {
        title: 'New Business Developer',
        image: '/img/employee/09.svg',
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'misc',
        description: 'Place house\nor garden',
    },
    E10: {
        title: 'Junior Vice President',
        image: '/img/employee/10.svg',
        promotion: ['E16', 'E17', 'E18', 'E19', 'E20'],
        begin: false,
        limited: false,
        salary: true,
        amount: 12,
        category: 'management',
        description: '3',
    },
    E11: {
        title: 'Luxuries Manager',
        image: '/img/employee/11.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'pricing',
        description: 'Price +$10',
    },
    E12: {
        title: 'Cart Operator',
        image: '/img/employee/12.svg',
        promotion: ['E21'],
        begin: false,
        limited: false,
        salary: true,
        distanceType: 'walk',
        distance: 2,
        amount: 6,
        category: 'drink',
        description: 'Get 2 drinks from\neach source on route',
    },
    E13: {
        title: 'Campaign Manager',
        image: '/img/employee/13.svg',
        promotion: ['E22'],
        begin: false,
        limited: false,
        salary: true,
        distanceType: 'walk',
        distance: 3,
        amount: 6,
        category: 'marketing',
        description: 'Place mailbox or\nlower, max duration 3',
    },
    E14: {
        title: 'Burger Cook',
        image: '/img/employee/14.svg',
        promotion: ['E23'],
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'food',
        description: 'Produce 3 burgers',
    },
    E15: {
        title: 'Pizza Cook',
        image: '/img/employee/15.svg',
        promotion: ['E24'],
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'food',
        description: 'Produce 3 pizzas',
    },
    E16: {
        title: 'Local Manager',
        image: '/img/employee/16.svg',
        begin: false,
        limited: false,
        salary: true,
        distanceType: 'walk',
        distance: 3,
        amount: 6,
        category: 'restaurant',
        description: 'Place new restaurant,\n"COMING SOON".\nDrive-in available',
    },
    E17: {
        title: 'Vice President',
        image: '/img/employee/17.svg',
        promotion: ['E25', 'E26', 'E27'],
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'management',
        description: '4',
    },
    E18: {
        title: 'Discount Manager',
        image: '/img/employee/18.svg',
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'pricing',
        description: 'Price -$3',
    },
    E19: {
        title: 'Recruiting Manager',
        image: '/img/employee/19.svg',
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'hr',
        description: 'Hire 1 person\nor $5 less salary',
        descriptionLabel: '2x:',
    },
    E20: {
        title: 'Coach',
        image: '/img/employee/20.svg',
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'hr',
        description: '2 training slots.\nMay train the same person two steps',
    },
    E21: {
        title: 'Truck Driver',
        image: '/img/employee/21.svg',
        promotion: ['E28'],
        begin: false,
        limited: false,
        salary: true,
        distanceType: 'walk',
        distance: 3,
        amount: 6,
        category: 'drink',
        description: 'Get 3 drinks from each source on route',
    },
    E22: {
        title: 'Brand  Manager',
        image: '/img/employee/22.svg',
        promotion: ['E29'],
        begin: false,
        limited: false,
        salary: true,
        distanceType: 'fly',
        distance: Infinity,
        amount: 6,
        category: 'marketing',
        description: 'Place airplane or\nlower, max duration 4',
    },
    E23: {
        title: 'Burger Chef',
        image: '/img/employee/23.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'food',
        description: 'Produce 8 burgers',
    },
    E24: {
        title: 'Pizza Chef',
        image: '/img/employee/24.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'food',
        description: 'Produce 8 pizzas',
    },
    E25: {
        title: 'Regional Manager',
        image: '/img/employee/25.svg',
        begin: false,
        limited: true,
        salary: true,
        distanceType: 'fly',
        distance: Infinity,
        amount: 3,
        category: 'restaurant',
        description: 'Place or move\nrestaurant, opens\nimmediately.\nDrive-in available',
    },
    E26: {
        title: 'Senior Vice President',
        image: '/img/employee/26.svg',
        promotion: ['E30', 'E31', 'E32'],
        begin: false,
        limited: false,
        salary: true,
        amount: 6,
        category: 'management',
        description: '5',
    },
    E27: {
        title: 'Guru',
        image: '/img/employee/27.svg',
        begin: true,
        limited: false,
        salary: true,
        amount: 3,
        category: 'hr',
        description: '3 training slots.\nMay train the same\nperson up to three steps',
    },
    E28: {
        title: 'Zeppelin Pilot',
        image: '/img/employee/28.svg',
        begin: false,
        limited: true,
        salary: true,
        distanceType: 'fly',
        distance: 4,
        amount: 3,
        category: 'drink',
        description: 'Get 2 drinks from\neach source on route,\nignore roads',
    },
    E29: {
        title: 'Brand Director',
        image: '/img/employee/29.svg',
        begin: false,
        limited: true,
        salary: true,
        distanceType: 'fly',
        distance: Infinity,
        amount: 3,
        category: 'marketing',
        description: 'Place radio or\nlower, max duration 5',
    },
    E30: {
        title: 'CFO',
        image: '/img/employee/30.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'misc',
        description: 'Add +50% to cash\nearned this round',
    },
    E31: {
        title: 'Executive Vice President',
        image: '/img/employee/31.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'management',
        description: '10',
    },
    E32: {
        title: 'HR Director',
        image: '/img/employee/32.svg',
        begin: false,
        limited: true,
        salary: true,
        amount: 3,
        category: 'hr',
        description: 'Hire 1 person or $5 less salary',
        descriptionLabel: '4x:',
    },
};
